name: exame_todo_list
description: A challenge given by Exame to prove knowledge. The app is a todolist
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  hive: ^2.0.4
  path_provider: ^2.0.2
  intl: ^0.17.0


  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1





dev_dependencies:
  build_runner: ^2.0.6
  mobx_codegen: ^2.0.1+3
  hive_generator: ^1.1.0
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.0
  mockito: ^5.0.12
  flutter_test:
    sdk: flutter


flutter_native_splash:
  image: assets/images/splash.png
  color: "FFFFFF"

flutter_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/background_icon.png"
  adaptive_icon_foreground: "assets/images/foreground_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Worksans
      fonts:
        - asset: assets/fonts/worksans_regular.ttf
          weight: 400
        - asset: assets/fonts/worksans_medium.ttf
          weight: 500
        - asset: assets/fonts/worksans_semibold.ttf
          weight: 600